NAME = amateria
SRC = main.cpp Ice.cpp AMateria.cpp Character.cpp Cure.cpp MateriaSource.cpp
INC = Ice.hpp AMateria.hpp Character.hpp ICharacter.hpp Cure.hpp IMateriaSource.hpp MateriaSource.hpp

ifdef DEBUG
	CC=clang++
	FLAGS = -Wall -Wextra -fsanitize=address -DDEBUG=1 -g -std=c++98
else
	CC=c++
	FLAGS = -Wall -Wextra -Werror
endif

OBJ = $(SRC:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(FLAGS) $(OBJ) -o $(NAME)

%.o: %.cpp $(INC)
	$(CC) $(FLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all
.PHONY: all clean fclean re
